name: StickyProtection
main: net.simplycrafted.StickyProtection.StickyProtection
author: Brianetta
website: https://github.com/Brianetta/StickyProtection
version: ${project.version}
api-version: 1.13
depend:
    - StickyLocks